sudo: false

language: node_js

node_js:
  - 'iojs'
  - '0.12'
  - '0.10'

env:
  CODECLIMATE_REPO_TOKEN: '29a8780ac2394110357650c690785230517c9e4a47116a314d2218e07629f97c'

before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g codeclimate-test-reporter

after_success:
  - istanbul cover _mocha -- -R spec ./test/*.js
  - codeclimate < ./coverage/lcov.info
